default_install_hook_types:
  - prepare-commit-msg

repos:
  - repo: local
    hooks:
      - id: llm-git-prepare-commit-msg
        name: llm prepare commit message
        description: Prepare commit message using LLM
        entry: llm git prepare-commit-msg
        language: python
        stages:
          - prepare-commit-msg
