[tools]
chezmoi = "latest"

[tasks.bump]
description = "Upgrade All"
depends = "bump:*"

[tasks."bump:gh"]
description = "Sync Github Extensions"
run = "gh extension upgrade --all"

[tasks."bump:docker"]
description = "Sync Docker Images"
run = [
  "orbctl start",
  "docker compose --project-name homelab --file ~/.config/services/compose.yaml pull",
  "docker compose --project-name homelab --file ~/.config/services/compose.yaml up --detach --force-recreate"
]
