name: homelab
services:
  bifrost:
    image: maximhq/bifrost
    container_name: bifrost
    restart: always
    labels:
      - dev.orbstack.domains=bifrost.orb.local
    volumes:
      - ./bifrost:/app/data
    environment:
      - MISTRAL_API_KEY
      - OPENCODE_API_KEY
      - NVIDIA_API_KEY
    dns:
      - 1.1.1.1
      - 8.8.8.8
