model: Bifrost:mistral/labs-devstral-small-2512
clients:
  - type: openai-compatible
    name: Bifrost
    api_base: http://bifrost.orb.local/openai/v1
    models:
      - name: mistral/devstral-2512
      - name: mistral/labs-devstral-small-2512
      - name: mistral/mistral-small-2603
      - name: mistral/mistral-medium-3.5
      - name: opencode/minimax-m2.5-free
