model: Bifrost:mistral/devstral-2512
clients:
  - type: openai-compatible
    name: Bifrost
    api_base: http://bifrost.orb.local/openai/v1
    models:
      - name: mistral/codestral-latest
      - name: mistral/devstral-2512
      - name: mistral/labs-devstral-small-2512
      - name: mistral/mistral-small-2603
      - name: mistral/mistral-large-latest
      - name: nvidia/minimaxai/minimax-m2.5
      - name: nvidia/moonshotai/kimi-k2.5
      - name: nvidia/nvidia/nemotron-3-super-120b-a12b
      - name: nvidia/openai/gpt-oss-120b
      - name: nvidia/stepfun-ai/step-3.5-flash
      - name: nvidia/qwen/qwen3.5-397b-a17b
      - name: nvidia/z-ai/glm5
      - name: opencode/minimax-m2.5-free
      - name: opencode/nemotron-3-super-free
