onboarding = false

[ui]
prompt_new_tab_name = false

agent_panel_sort = "spaces"

show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false

[keys]
previous_workspace = "ctrl+["
next_workspace = "ctrl+]"
previous_agent = "ctrl+alt+["
next_agent = "ctrl+alt+]"
open_worktree = "prefix+shift+o"

[[keys.command]]
key = "prefix+u"
type = "pane"
command = "lazygit"
description = "Lazygit"

[[keys.command]]
key = "prefix+y"
type = "pane"
command = "yazi"
description = "Yazi"

[[keys.command]]
key = "prefix+i"
type = "pane"
command = "lazydocker"
description = "Lazydocker"

[theme]
name = "catppuccin"
auto_switch = false

[experimental]
pane_history = true
switch_ascii_input_source_in_prefix = true
