[tools]
"github:badlogic/pi-mono" = "latest"
"github:can1357/oh-my-pi" = "latest"
"github:just-every/code" = { version = "latest", bin = "every-code" }
"github:Loongphy/codext" = "latest"
"github:mr-kelly/freecode" = "latest"
"npm:@github/copilot" = "latest"
"npm:command-code" = "latest"
"pipx:llm" = "latest"
"pipx:mistral-vibe" = "latest"
amp = "latest"
claude = "latest"
codex = "latest"
jules = "latest"
opencode = "latest"
qwen = "latest"
