[tools]
"github:derekwisong/datui" = "latest"  # Data viewer
"github:hymkor/csvi" = "latest"  # CSV Editor
"github:neilotoole/sq" = "latest"  # jq-style data wrangler
"github:riii111/sabiql" = "latest"
"npm:neonctl" = "latest"
"pipx:pgcli" = "latest"
"pipx:sqlit-tui" = "latest"
