[tools]
# "github:lusingander/serie" = "latest" # git commit
# "github:SierraSoftworks/git-tool" = "latest" # try-rs
"cargo:deff" = "latest"  # Git diff
"github:affromero/gitpane" = "latest"
"github:dagimg-dot/gitsnip" = "latest"
"npm:difit" = "latest"  # Git diff
"pipx:git-aggregator" = "latest"
