[tools]
"cargo:deff" = "latest"  # Git diff
"github:affromero/gitpane" = "latest"
"github:akunzai/gistui" = "latest"
"github:dagimg-dot/gitsnip" = "latest"
"github:lusingander/serie" = "latest"  # git commit
"npm:difit" = "latest"  # Git diff
"pipx:git-aggregator" = "latest"
hunk = "latest"
