[tools]
# "github:boxlite-ai/boxrun" = "latest" # not working
# "github:pigmej/aisanity" = "latest"
# "npm:ccmanager" = "latest"
"github:rtk-ai/rtk" = "latest"  # Token reducer
"npm:@ccusage/codex" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@loongphy/codex-auth" = "latest"
"npm:@tobilu/qmd" = "latest"  # Quick Markdown Search
"npm:ccusage" = "latest"
"npm:context-mode" = "latest"
"npm:defuddle" = "latest"  # HTML to Markdown
"npm:skills" = "latest"
"npm:vibe-kanban" = "latest"
"pipx:git+https://github.com/antoniorodr/memo.git" = { version = "latest", uvx_args = "--python 3.13" }
"pipx:git+https://github.com/github/spec-kit.git" = "latest"
"pipx:skill-seekers" = "latest"
