[tools]
# "github:piqoni/hn-text" = "latest" # hackernews_tui
# "pipx:rich-cli" = "latest" # gum
"github:aome510/hackernews-TUI" = "latest"
"github:ramonvermeulen/whosthere" = "latest"
"github:textfuel/lazyjira" = "latest"
superfile = "latest"
