[tools]
bun = "latest"
chezmoi = "latest"
fnox = "latest"
node = "24"
python = "3.12"
rust = "latest"
uv = "latest"

[settings]
env_cache = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "create|source"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
_.fnox-env = { tools = true }
CFLAGS = "-I/opt/homebrew/opt/openssl@3/include"
LDFLAGS = "-L/opt/homebrew/opt/openssl@3/lib -Wl,-no_warn_duplicate_libraries"
OPENCODE_ENABLE_EXA = true
HOMEBREW_NO_AUTO_UPDATE = true
HOMEBREW_NO_ENV_HINTS = true
LLM_CMD_MODEL = "gpt-5.4-mini"
